# Generated by Django 3.1.13 on 2022-05-12 15:25

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_pdfdocument_is_signed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.pdfdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
