# Generated by Django 3.1.13 on 2022-05-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models.file.base
import main.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('name', models.IntegerField(blank=True, choices=[(1, 'Default'), (2, 'Profession')], null=True)),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('place_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=19, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=19, null=True)),
                ('summary', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('name', models.IntegerField(choices=[(1, 'Home'), (2, 'Work')], default=1)),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('is_physical', models.BooleanField(default=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='entities', to='main.Activity')),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('phone_number', models.TextField()),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.entity')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en-us', max_length=10)),
                ('doc_is_valid', models.BooleanField(null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
            bases=('main.entity',),
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('informations', models.TextField(blank=True, default=None, null=True)),
                ('original_filename', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('image_file', models.ImageField(blank=True, default=None, null=True, upload_to=main.models.file.base.BaseFile.generate_filename)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.entity')),
            ],
            options={
                'abstract': False,
            },
            bases=(main.utils.UidMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EntityPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('phone_type', models.IntegerField(choices=[(1, 'Mobile'), (2, 'Emergency'), (3, 'Home'), (4, 'Work')], default=1)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entity')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phone')),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.address')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.addresstype')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entity')),
            ],
            options={
                'verbose_name': 'Entity address',
                'verbose_name_plural': 'Entity addresses',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='addresses',
            field=models.ManyToManyField(related_name='entities', through='main.EntityAddress', to='main.Address'),
        ),
        migrations.AddField(
            model_name='entity',
            name='phones',
            field=models.ManyToManyField(blank=True, related_name='entities', through='main.EntityPhone', to='main.Phone'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.activitytype'),
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.activity',),
        ),
        migrations.CreateModel(
            name='PersonProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profession')),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('used', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_confirmation', to='main.person')),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='main.imagefile'),
        ),
        migrations.AddField(
            model_name='person',
            name='professions',
            field=models.ManyToManyField(related_name='persons', through='main.PersonProfession', to='main.Profession'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FormationSession',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('num_present_trainee', models.IntegerField(default=0)),
                ('doc_has_been_sent', models.BooleanField(default=False)),
                ('foad', models.BooleanField(default=False)),
                ('prerequis_formation', models.BooleanField(default=False)),
                ('completed_videochat_sessions', models.IntegerField(blank=True, default=0, null=True)),
                ('opco_name', models.IntegerField(choices=[(1, 'OpcoSanté'), (2, 'Opco2I'), (3, 'OpcoMobilités'), (4, 'OpcoEp'), (5, 'OpCommerce'), (6, 'Akto'), (7, 'Ocapiat'), (8, 'Afdas'), (9, 'Atlas'), (10, 'Uniformation'), (11, 'Constructys')], default=1)),
                ('date_autorised_start', models.DateField()),
                ('date_autorised_end', models.DateField()),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('training_duration', models.IntegerField(default=0)),
                ('training_done', models.IntegerField(blank=True, default=0, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('agreement_recieved', models.BooleanField(default=False)),
                ('convention_sent', models.BooleanField(default=False)),
                ('convention_signed', models.BooleanField(default=False)),
                ('convocation_sent', models.BooleanField(default=False)),
                ('emargement_recieved', models.BooleanField(default=False)),
                ('attest_and_qcm_sent', models.BooleanField(default=False)),
                ('bill_paid', models.BooleanField(default=False)),
                ('date_bill_sent', models.DateField(blank=True, null=True)),
                ('date_bill_paid', models.DateField(blank=True, null=True)),
                ('teacher_price', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('ammount_already_paid', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('old_num_formation', models.CharField(default='DC-00000', max_length=35)),
                ('date_creation_formation', models.DateField()),
                ('room_name', models.SlugField(default=None, null=True)),
                ('commercial', models.ForeignKey(limit_choices_to={'groups__name': 'commercial'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commercial', to=settings.AUTH_USER_MODEL)),
                ('teacher_name', models.ForeignKey(limit_choices_to={'groups__name': 'teacher'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('training_site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.address')),
                ('trainee', models.ManyToManyField(to='main.Person')),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_update', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('link_type', models.IntegerField(blank=True, choices=[(1, 'Teacher ↔ Learner')], default=None, null=True)),
                ('dst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='main.entity')),
                ('src', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='src', to='main.entity')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
                'unique_together': {('src', 'dst', 'link_type')},
            },
        ),
    ]
