# Generated by Django 4.1.2 on 2023-01-29 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models.file.base
import main.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "name",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Default"), (2, "Profession")],
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "place_id",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=19,
                        null=True,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=250, null=True)),
                ("details", models.TextField(blank=True, default=None, null=True)),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default=None, max_length=25, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="AddressType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "name",
                    models.IntegerField(choices=[(1, "Home"), (2, "Work")], default=1),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "name",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Emargement"),
                            (2, "Contrat de partenariat formateur"),
                            (3, "Convocation"),
                            (4, "Qcm"),
                            (5, "Reglement interieur"),
                            (6, "Compte Rendu de formation"),
                            (7, "Ordre de mission"),
                            (8, "Attestation de fin de stage"),
                            (10, "Bon de commande"),
                            (11, "Kbis"),
                            (12, "Rib"),
                            (13, "Declaration Insee"),
                            (9, "Convention de formation"),
                        ],
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                ("is_physical", models.BooleanField(default=True)),
                (
                    "activities",
                    models.ManyToManyField(
                        blank=True, related_name="entities", to="main.activity"
                    ),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormationSession",
            fields=[
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("num_present_trainee", models.IntegerField(default=0)),
                ("doc_has_been_sent", models.BooleanField(default=False)),
                ("foad", models.BooleanField(default=False)),
                ("prerequis_formation", models.BooleanField(default=False)),
                (
                    "completed_videochat_sessions",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "teacher_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                (
                    "opco_name",
                    models.IntegerField(
                        choices=[
                            (1, "AKTO Réseau Fafih"),
                            (2, "AFDAS"),
                            (3, "AFDAS (Intermittent)"),
                            (4, "OPCO ATLAS"),
                            (5, "CAISSE DES DEPOTS ET CONSIGNATIONS"),
                            (6, "OPCALIA"),
                            (7, "AGEFICE"),
                            (8, "FP"),
                            (9, "AKTO Réseau Intergros"),
                            (10, "OPCOMMERCE"),
                            (11, "OPCO EP"),
                            (12, "OPCOmobilité"),
                            (13, "OCAPIAT"),
                            (14, "OPCO 2I"),
                        ],
                        default=1,
                    ),
                ),
                ("date_autorised_start", models.DateField()),
                ("date_autorised_end", models.DateField()),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("training_duration", models.IntegerField(default=0)),
                (
                    "training_done",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "old_num_formation",
                    models.CharField(default="DC-00000", max_length=35),
                ),
                ("date_creation_formation", models.DateField(auto_now=True)),
                (
                    "commercial",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "commercial"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commercial",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Objectifs_peda",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                ("phone_number", models.TextField()),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "entity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.entity",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        blank=True, default="non renseignee", max_length=100, null=True
                    ),
                ),
                (
                    "num_decla_activite",
                    models.CharField(
                        blank=True, default="non renseignee", max_length=100, null=True
                    ),
                ),
                (
                    "num_siret",
                    models.CharField(
                        blank=True, default="non renseignee", max_length=100, null=True
                    ),
                ),
                (
                    "code_ape",
                    models.CharField(blank=True, default=0, max_length=100, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("numb_employees", models.IntegerField(default=0)),
                (
                    "Industry",
                    models.CharField(
                        blank=True, default="non renseignee", max_length=100, null=True
                    ),
                ),
            ],
            bases=("main.entity",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "entity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.entity",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en-us",
                        max_length=10,
                    ),
                ),
                ("user_verification_code", models.IntegerField(default=1658)),
                ("doc_is_valid", models.BooleanField(null=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
            bases=("main.entity",),
        ),
        migrations.CreateModel(
            name="VideoChat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                ("session", models.IntegerField(blank=True, default=1, null=True)),
                ("date_link_sent", models.DateField(auto_now_add=True)),
                ("date_start", models.DateField(default=None)),
                ("time_start", models.TimeField(default=None)),
                ("date_end", models.DateField(default=None)),
                ("time_end", models.TimeField(default=None)),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, null=True, unique=True
                    ),
                ),
                ("finished_session", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formation_session",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.formationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                ("informations", models.TextField(blank=True, default=None, null=True)),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=main.models.file.base.BaseFile.generate_filename,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.entity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(main.utils.UidMixin, models.Model),
        ),
        migrations.AddField(
            model_name="formationsession",
            name="objectifs_peda",
            field=models.ManyToManyField(
                blank=True, null=True, to="main.objectifs_peda"
            ),
        ),
        migrations.AddField(
            model_name="formationsession",
            name="teacher_name",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formationsession",
            name="training_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.address",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, null=True, unique=True
                    ),
                ),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "formation_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.formationsession",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        limit_choices_to={"groups__name": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_chat",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.videochat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityPhone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "phone_type",
                    models.IntegerField(
                        choices=[
                            (1, "Mobile"),
                            (2, "Emergency"),
                            (3, "Home"),
                            (4, "Work"),
                        ],
                        default=1,
                    ),
                ),
                ("comment", models.TextField(blank=True, default=None, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.entity"
                    ),
                ),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.phone"
                    ),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                ("comment", models.TextField(blank=True, default=None, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.address"
                    ),
                ),
                (
                    "address_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.addresstype",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.entity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity address",
                "verbose_name_plural": "Entity addresses",
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="addresses",
            field=models.ManyToManyField(
                related_name="entities", through="main.EntityAddress", to="main.address"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="phones",
            field=models.ManyToManyField(
                blank=True,
                related_name="entities",
                through="main.EntityPhone",
                to="main.phone",
            ),
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                ("informations", models.TextField(blank=True, default=None, null=True)),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "actual_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=main.models.file.base.BaseFile.generate_filename,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.entity",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.documenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(main.utils.UidMixin, models.Model),
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.activitytype",
            ),
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.activity",),
        ),
        migrations.CreateModel(
            name="PersonProfession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.person"
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.profession",
                    ),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonConfirmation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("used", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_confirmation",
                        to="main.person",
                    ),
                ),
            ],
            options={
                "ordering": ["date_v_start"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="person",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persons",
                to="main.imagefile",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="professions",
            field=models.ManyToManyField(
                related_name="persons",
                through="main.PersonProfession",
                to="main.profession",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PdfDocument",
            fields=[
                (
                    "documentfile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.documentfile",
                    ),
                ),
                ("is_signed", models.BooleanField(default=False)),
                ("numb_of_signed_trainees", models.IntegerField(default=0)),
                ("verification_code", models.IntegerField(default=1658)),
                (
                    "formation_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.formationsession",
                    ),
                ),
                (
                    "is_signed_by",
                    models.ManyToManyField(
                        related_name="signed_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "type_of_document",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.documenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("main.documentfile",),
        ),
        migrations.AddField(
            model_name="formationsession",
            name="client_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="formationsession",
            name="trainee",
            field=models.ManyToManyField(blank=True, null=True, to="main.person"),
        ),
        migrations.CreateModel(
            name="EventMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="main.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "user")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="trainee",
            field=models.ManyToManyField(related_name="trainee", to="main.person"),
        ),
        migrations.CreateModel(
            name="EntityLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "date_last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last changed"),
                ),
                (
                    "date_v_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="V. start"
                    ),
                ),
                (
                    "date_v_end",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="V. end"
                    ),
                ),
                (
                    "link_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Teacher ↔ Learner")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "dst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dst",
                        to="main.entity",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="src",
                        to="main.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation",
                "verbose_name_plural": "Relations",
                "unique_together": {("src", "dst", "link_type")},
            },
        ),
        migrations.AddField(
            model_name="company",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.entityaddress",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_phone",
                to="main.phone",
            ),
        ),
    ]
