# Generated by Django 3.1.13 on 2022-05-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationsession',
            name='room_name',
        ),
    ]
