# Generated by Django 3.1.13 on 2022-05-11 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_formationsession_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.entity')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('raison_sociale', models.CharField(blank=True, default='non renseignee', max_length=100, null=True)),
                ('num_decla_activite', models.CharField(blank=True, default='non renseignee', max_length=100, null=True)),
                ('num_siret', models.CharField(blank=True, default='non renseignee', max_length=100, null=True)),
                ('code_ape', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('numb_employees', models.IntegerField(default=0)),
                ('Industry', models.CharField(blank=True, default='non renseignee', max_length=100, null=True)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.entityaddress')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_phone', to='main.phone')),
            ],
            bases=('main.entity',),
        ),
        migrations.AddField(
            model_name='formationsession',
            name='client_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
            preserve_default=False,
        ),
    ]
