# Generated by Django 3.1.13 on 2022-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220511_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationsession',
            name='agreement_recieved',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='ammount_already_paid',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='attest_and_qcm_sent',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='bill_paid',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='convention_sent',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='convention_signed',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='convocation_sent',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='date_bill_paid',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='date_bill_sent',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='emargement_recieved',
        ),
        migrations.RemoveField(
            model_name='formationsession',
            name='teacher_price',
        ),
        migrations.AlterField(
            model_name='formationsession',
            name='date_creation_formation',
            field=models.DateField(auto_now=True),
        ),
    ]
