# Generated by Django 3.1.13 on 2022-05-11 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220511_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
