# Generated by Django 3.1.13 on 2022-05-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_documentfile_documenttype_event_eventmember_pdfdocument_videochat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videochat',
            name='link',
        ),
        migrations.RemoveField(
            model_name='videochat',
            name='message',
        ),
    ]
