# Generated by Django 3.1.13 on 2022-05-12 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20220511_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='is_signed_by',
            field=models.ManyToManyField(related_name='signed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
