# Generated by Django 3.1.13 on 2022-09-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220913_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationsession',
            name='teacher_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
