# Generated by Django 3.1.13 on 2022-10-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_formationsession_teacher_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationsession',
            name='objectifs_peda',
            field=models.TextField(null=True),
        ),
    ]
